---
title: "CoGAPS on SciServer"
date: "`r format(Sys.time(), '%B, %Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: "This introductory course will provide a quick overview of how CoGAPS can be run through the SciServer compute platform."
favicon: assets/dasl_favicon.ico
output:
    bookdown::word_document2:
      toc: true
---

# About this Course {-}

This introductory course will provide a quick overview of how CoGAPS can provide new insights into single cell datasets. Through these exercises you will analyze a real dataset using the SciServer compute platform.

## Available course formats

This course is available in multiple formats which allows you to take it in the way that best suits your needs. You can take it for certificate which can be for free or fee.

- The material for this course can be viewed without login requirement on this [Bookdown website](https://practicalgenomics.github.io/cogaps-on-sciserver/). This format might be most appropriate for you if you rely on screen-reader technology.
- This course can be taken for [free certification through Leanpub](LINK HERE).
- Our courses are open source, you can find the [source material for this course on GitHub](https://github.com/PracticalGenomics/cogaps-on-sciserver).
